apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.19.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: configmapvol
      mountPath: /etc/nginx
    - name: secretvol
      mountPath: /etc/nginx/conf

  volumes:
  - name: configmapvol
    configMap:
      name: nginx-config
  - name: secretvol
    secret:
      secretName: nginx-htpasswd