apiVersion: v1
kind: Pod
metadata:
  name: shipping-web
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
  initContainers:
  - name: shipping-init
    image: busybox
    command: ["sh", "-c", "nslookup shipping-svc"]