apiVersion: v1
kind: Pod
metadata:
  name: my-command-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['echo']

    - name: myapp-arg-container
      image: busybox
      command: ['echo']
      args: ['This is my custom argument']

    - name: myapp-container-port
      image: nginx
      ports:
        - containerPort: 80
  restartPolicy: Never